apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-autoscaler
rules:
- apiGroups: [""]
  resources:
    - events
    - endpoints
    - pods/eviction
    - pods/status
    - nodes
    - pods
    - services
    - replicationcontrollers
    - persistentvolumeclaims
    - persistentvolumes
  verbs: ["create","patch","update","watch","list","get"]
- apiGroups: ["apps"]
  resources: ["daemonsets","replicasets","statefulsets","deployments"]
  verbs: ["watch","list","get"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses","csinodes","csidrivers","csistoragecapacities"]
  verbs: ["watch","list","get"]
- apiGroups: ["batch","extensions"]
  resources: ["jobs","cronjobs"]
  verbs: ["watch","list","get"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["create","get","list","update","patch"]
- apiGroups: ["autoscaling.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
