---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: http-production
spec:
  acme:
    email: your-email@devopsbyexample.com  # replace with your email for letsencrypt certificate renewal notification
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: http-production-cluster-issuer
    solvers:
      - http01:
          ingress:
            ingressClassName: external-nginx